### ISSUE TITLE
Needs some documentation

### ISSUE THREAD

**Issue by fflorent** [clochix/polybios#3]
I think the application deserves some user documentation. Yes, because... sorry... I am not sure what the application offers nor where to start :)

Florent

**Comment by clochix** [comment]
Thanks for your interest @fflorent. Unfortunately, I think this application may be considered dead. It need a backend to securely store your keyring, and I didn't find one easy to install and use. So this application is pretty useless. Sorry.

**Comment by fflorent** [comment]
No problem @clochix. Thanks for the update.

Florent

2015-09-27 13:17 GMT+02:00 Clochix <notifications@github.com>:
